# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b627846ffce7af305def350e1afab967ee4a6af6a71c1fa56606b9936472f0a263671a043a13615aea9cd669c83d3bdb0873337790c19eb2c0313ef02f1cb12

test:
  secret_key_base: 065cef462c39baaad2e92ae47b347802e7c98f539d57fef9bd910341fc1d8c21ff330d56acfa639ee01e8c59825458816ea2212eddef4d4c3b4c454b7599cbad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
